<?php

/**
 * Defining the Constants
 */
define('LENDINGFORM_ENTITY', 'enquiry');
define('LENDINGFORM_BASE_TABLE', 'enquiry');

/**
 * Defining Permission Constant
 */
define('PERM_LENDINGFORM_CREATE', 'create enquiry entity');
define('PERM_LENDINGFORM_EDIT', 'edit enquiry entity');
define('PERM_LENDINGFORM_DELETE', 'delete enquiry entity');
define('PERM_LENDINGFORM_VIEW', 'view enquiry entity');
define('PERM_ADMINISTER_LENDINGFORM', 'administer enquiry entity');

/**
 * Defining Configuration Constants
 */
define('LENDINGFORM_ADMIN_CONFIGURE', 'enquiry');
define('LENDINGFORM_CONFIGURE_PAGE', 'enquiry');

/**
 * Permission Constants Defined
 */
define('LENDINGFORM_ACCESS_ALLOW', 'allow');
define('LENDINGFORM_ACCESS_DENY', 'deny');
define('LENDINGFORM_ACCESS_IGNORE', 'ignore');

/**
 * These are what update options
 */
 
define('TREND_OPEN', 0);
define('TREND_IN_PROGRESS', 1);
define('TREND_FUNDED', 2);
define('TREND_CLOSED', 3);
 